/*
 * This file was NOT generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */



//CONFIGURATION IN CRYPTION
plugins {
    id("buildlogic.java-library-conventions")
}


dependencies {
    implementation("org.bouncycastle:bcprov-jdk15on:1.70") // use Bouncy Castle 
}