/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */



//CONFIGURATION IN NETWORK
plugins {
    id("buildlogic.java-library-conventions")
}
