/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */


//CONFIGURATION IN APP
plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    //implementation("org.apache.commons:commons-text")
    implementation(project(":network"))
    implementation(project(":database"))
    implementation(project(":cryption"))
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
