/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;
import java.util.Scanner;

import org.example.list.LinkedList;

import static org.example.utilities.StringUtils.join;
import static org.example.utilities.StringUtils.split;
import static org.example.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

/****************************************************************************************/
class KeyboardInput {  
    private static Scanner scanner = new Scanner(System.in); // share Scanner instance

    public static String takeInput() {  
        return scanner.nextLine();
    }

    public static void closeScanner() {
        scanner.close();
    }
}

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));

    /*************************************************************************************/
        Boolean working = false;

        while(!working){ // check configuration before start
            System.out.print("Ready to pass through? (check your configuration before say \"yes\")\n default: yes>");

            String userInput = KeyboardInput.takeInput(); 

            if (userInput.equals("n")){
                throw new RuntimeException("USER entered No, program exiting....");
            }else if (userInput.equals("") || userInput.equals("y")){
                working = true;
                System.out.println("Welcome to Gensokyo, starting....");
            }else{
                System.out.println("Illegal input, please do again.");
            }
        }
        
        KeyboardInput.closeScanner(); 

    }
}


